config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#top"
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  resource :user, only: %i[new create destroy]

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :top_rated
      get :bookmarks
      get :scheduled
      get :received
      get :search_tags
      get :recommended
    end
  end

  resources :bookmarks, only: %i[create destroy]

  resource :profile, only: %i[show edit update]

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_post_id  (post_id)
#  index_comments_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (post_id => posts.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, length: { maximum: 65_535 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    if comment.save
      redirect_to post_path(comment.post), success: t('defaults.message.created', item: Comment.model_name.human)
    else
      redirect_to post_path(comment.post), danger: t('defaults.message.not_created', item: Comment.model_name.human)
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
    redirect_to request.original_url, success: t('defaults.message.deleted', item: Comment.model_name.human)
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/views/comments/_comment.html.erb
<tr>
  <td style="width: 60px">
    <%= image_tag comment.user.avatar.url, class: 'rounded-circle', size: '50x50' %>
  </td>
  <td>
    <h3 class="small">
      <% if comment.user.nickname.present? %>
        <%= comment.user.nickname %>
      <% else %>
        <%= comment.user.name %>
      <% end %>
    </h3>
    <div id="js-comment-25">
      <p><%= simple_format(comment.body) %></p>
    </div>
  </td>

  <% if current_user && current_user.own?(comment) %>
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to comment_path(comment),
                      class: 'link-color-black',
                      data: { turbo_method: :delete, turbo_confirm: t('defaults.message.delete_confirm') } do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2">
    <table class="table">
      <%= render comments %>
    </table>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row mb-3">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: comment, url: [post, comment], local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control mb-3', row: '4', placeholder: Comment.human_attribute_name(:body) %>
      <%= f.submit t('defaults.post'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>