config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#top"
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  resource :user, only: %i[new create destroy]

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :top_rated
      get :bookmarks
      get :scheduled
      get :received
      get :search_tags
      get :recommended
    end
  end

  resources :bookmarks, only: %i[create destroy]

  resource :profile, only: %i[show edit update]

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
end

app/views/shared/_before_login_header.html.erb
<header class="sticky-top">
  <div class="container">
    <nav class="navbar navbar-expand navigation">

      <%= link_to '飯テログ', root_path, class: 'navbar-brand text-white fw-bold fs-4' %>


      <div class="ms-auto" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto main-nav align-items-center me-3">
          <li class="me-3">
            <a href="https://lin.ee/zckTAAt"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_fixed_footer.html.erb
<footer class="fixed-bottom">
  <nav class='navbar navbar-expand navigation navbar-light bg-light'>
    <div class='container-fluid'>
      <ul class='navbar-nav d-flex justify-content-center main-nav align-items-center w-100'>
        <li class='nav-item flex-grow-1 text-center'>
          <%= link_to posts_path, class: 'dropdown-item d-flex flex-column align-items-center' do %>
            <i class="fa-solid fa-bowl-food fs-5"></i>
            <%= t('defaults.index') %>
          <% end %>
        </li>
        <li class='nav-item flex-grow-1 text-center'>
          <%= link_to new_post_path, class: 'dropdown-item d-flex flex-column align-items-center' do %>
            <i class="bi bi-send-fill fs-5"></i>
            <%= t('posts.new.title') %>
          <% end %>
        </li>
        <li class='nav-item flex-grow-1 text-center'>
          <%= link_to received_posts_path, class: 'dropdown-item d-flex flex-column align-items-center' do %>
            <i class="bi bi-gift-fill fs-5"></i>
            <%= t('posts.received.title') %>
          <% end %>
        </li>
        <li class='nav-item flex-grow-1 text-center'>
          <%= link_to scheduled_posts_path, class: 'dropdown-item d-flex flex-column align-items-center' do %>
            <i class="bi bi-calendar-check-fill fs-5"></i>
            <%= t('posts.scheduled.title') %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</footer>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class="footer-bottom border-top pt-3">
  <div class="container">
    <div class="copyright text-center mb-2">
      <%=link_to t('static_pages.terms.title'), terms_path, class: "px-1 link-dark text-decoration-none" %>
      <%=link_to t('static_pages.privacy.title'), privacy_path, class: "px-1 link-dark text-decoration-none" %>
      <%=link_to t('static_pages.contact.title'), "https://docs.google.com/forms/d/e/1FAIpQLSerP-M1KxL-wgICmzZ-k2A1aC3VKuiJ52oFYlIHmXc9AVyVXg/viewform?usp=sf_link", class: "px-1 link-dark text-decoration-none" %>
    </div>
    <div class="copyright text-center">
      <p><%= t('defaults.copyright') %></p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class='sticky-top'>
  <nav class='navbar navbar-expand-lg navigation navbar-light'>
    <div class="container">
      <%= link_to '飯テログ', root_path, class: 'navbar-brand text-white fw-bold fs-4' %>

      <div class='d-block d-lg-none'>
        <button class=' btn btn-link' type='button' data-bs-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
          <%= image_tag current_user.avatar.url, class: 'rounded-circle', size: '40x40' %>
        </button>
        <div class='dropdown-menu dropdown-menu-end'>
          <% if current_user.nickname.present? %>
            <%= current_user.nickname %>
          <% else %>
            <%= current_user.name %>
          <% end %>
          <div class='dropdown-divider'></div>
          <%= link_to t('profiles.show.title'), profile_path, class: 'dropdown-item' %>
          <%= link_to t('posts.bookmarks.title'), bookmarks_posts_path, class: 'dropdown-item' %>
          <%= link_to t('defaults.logout'), user_path(@user), data: { turbo_method: :delete }, class: 'dropdown-item' %>
          <%= link_to t('defaults.back_talk'), 'https://line.me/R/ti/p/@910svtxk', class: 'dropdown-item' %>
        </div>
      </div>

      <div class='collapse navbar-collapse d-none d-lg-block' id='navbarSupportedContent'>
        <ul class='navbar-nav ms-auto me-3 main-nav align-items-center'>
          <li class='nav-item dropdown dropdown-slide'>
            <a href='#' class='nav-link' data-bs-toggle='dropdown' aria-haspopup='true' aria-expanded='false' id='header-profile'>
              <%= image_tag current_user.avatar.url, class: 'rounded-circle mr15', size: '40x40' %>
            </a>
            <div class='dropdown-menu dropdown-menu-end'>
              <div class='dropdown-item'>
                <% if current_user.nickname.present? %>
                  <%= current_user.nickname %>
                <% else %>
                  <%= current_user.name %>
                <% end %>
              </div>
              <div class='dropdown-divider'></div>
              <%= link_to t('profiles.show.title'), profile_path, class: 'dropdown-item' %>
              <%= link_to t('posts.bookmarks.title'), bookmarks_posts_path, class: 'dropdown-item' %>
              <%= link_to t('defaults.logout'), user_path(@user), data: { turbo_method: :delete }, class: 'dropdown-item' %>
              <%= link_to t('defaults.back_talk'), 'https://line.me/R/ti/p/@910svtxk', class: 'dropdown-item' %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>