config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#top"
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  resource :user, only: %i[new create destroy]

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :top_rated
      get :bookmarks
      get :scheduled
      get :received
      get :search_tags
      get :recommended
    end
  end

  resources :bookmarks, only: %i[create destroy]

  resource :profile, only: %i[show edit update]

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :bigint           not null, primary key
#  content      :text             not null
#  food_image   :string
#  published    :boolean          default(FALSE), not null
#  published_at :datetime
#  title        :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  author_id    :bigint           not null
#  user_id      :bigint
#
# Indexes
#
#  index_posts_on_author_id  (author_id)
#  index_posts_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (author_id => users.id)
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  mount_uploader :food_image, FoodImageUploader

  acts_as_taggable

  belongs_to :user
  belongs_to :author, class_name: "User"
  has_many :deliveries, dependent: :destroy
  has_many :recipients, through: :deliveries, source: :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 65_535 }

  after_create_commit :notify_line
  after_create_commit :schedule_publication

  scope :with_associations, -> { includes(:deliveries, :recipients, :comments, :bookmarks) }
  scope :tag_name_cont, ->(tag_name) { tagged_with(tag_name) }

  ROOT_URL = "https://meshitelog.com"

  def self.ransackable_scopes(_auth_object = nil)
    [:tag_name_cont]
  end

  def self.ransackable_associations(_auth_object = nil)
    ["bookmarks", "comments", "user"]
  end

  def self.ransackable_attributes(_auth_object = nil)
    ["content", "created_at", "title"]
  end

  def future_reserved_post?(current_user)
    published_at.present? && published_at > Time.current && user != current_user
  end

  # nicknameがあればnicknameを、なければnameを返す
  def sender_name
    user.nickname || user.name
  end

  # 各投稿詳細ページのURLを返す
  def post_url
    "#{ROOT_URL}/posts/#{id}"
  end

  def notify_line
    # 予約投稿か否かを判定
    return unless published?

    line_client = LineClient.new
    flex_contents = {
      type: "bubble",
      header: {
        type: 'box',
        layout: 'vertical',
        contents: [
          {
            type: 'text',
            text: "飯が届きました！",
            weight: "bold",
            size: "xl",
            wrap: true
          }
        ]
      },
      hero: {
        type: "image",
        url: food_image.url,
        size: "full",
        aspectRatio: "20:13",
        aspectMode: "cover",
        action: {
          type: "uri",
          uri: post_url
        }
      },
      body: {
        type: "box",
        layout: "vertical",
        contents: [
          {
            type: "text",
            text: title,
            weight: "bold",
            size: "xl",
            wrap: true
          },
          {
            type: "box",
            layout: "vertical",
            margin: "lg",
            spacing: "sm",
            contents: [
              {
                type: "box",
                layout: "baseline",
                spacing: "sm",
                contents: [
                  {
                    type: "text",
                    text: "#{sender_name} さんより",
                    wrap: true,
                    color: "#666666",
                    size: "sm",
                    flex: 5
                  }
                ]
              },
              {
                type: "box",
                layout: "baseline",
                spacing: "sm",
                contents: [
                  {
                    type: "text",
                    text: content,
                    wrap: true,
                    color: "#666666",
                    size: "md",
                    flex: 5
                  }
                ]
              }
            ]
          }
        ]
      },
      footer: {
        type: "box",
        layout: "vertical",
        spacing: "sm",
        contents: [
          {
            type: "button",
            style: "link",
            height: "sm",
            action: {
              type: "uri",
              label: "詳細を見る",
              uri: post_url
            }
          },
          {
            type: "box",
            layout: "vertical",
            contents: [],
            margin: "sm"
          }
        ],
        flex: 0
      }
    }

    deliveries.each do |delivery|
      line_client.push_flex_message(delivery.user.line_user_id, "飯が届きました！： #{title}", flex_contents)
    end
  end

  def schedule_publication
    # `published_at`が設定されていれば予約投稿、そうでなければ即時投稿
    if published_at.present?
      PublishPostJob.set(wait_until: published_at).perform_later(self)
    else
      update(published: true)
      notify_line
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :bookmarks, :scheduled, :received]
  before_action :set_recipient_ids, only: [:create, :update]
  before_action :set_post, only: %i[edit update destroy]

  def index
    @q = Post.where('published_at IS NULL OR published_at <= ?', Time.current).ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user, :taggings).order(created_at: :desc)

    @posts = @posts.tagged_with("#{params[:tag_name]}") if params[:tag_name]

    @posts = @posts.page(params[:page])

    render partial: 'post', collection: @posts, as: :post, status: :ok if request.xhr?
  end

  # 高評価順
  def top_rated
    @q = Post.left_joins(:bookmarks)
      .select('posts.*, COUNT(bookmarks.post_id) AS bookmarks_count')
      .group('posts.id')
      .order('bookmarks_count DESC')
      .where('published_at IS NULL OR published_at <= ?', Time.current)
      .ransack(params[:q])

    @posts = @q.result(distinct: true).includes(:user, :taggings)

    @posts = @posts.tagged_with("#{params[:tag_name]}") if params[:tag_name]

    @posts = @posts.page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    # 予約投稿で現在時刻よりも後の投稿で、かつ現在のユーザーが投稿の作成者でない場合
    if @post.future_reserved_post?(current_user)
      redirect_to posts_path
    else
      @comment = Comment.new
      @comments = @post.comments.includes(:user).order(created_at: :desc)
    end
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = current_user.posts.build(post_params)
    @post.author = current_user

    if @post.save
      redirect_to posts_path, success: t('defaults.message.created', item: Post.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_created', item: Post.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, success: t('defaults.message.updated', item: Post.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: Post.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, success: t('defaults.message.deleted', item: Post.model_name.human)
  end

  # お気に入り投稿一覧
  def bookmarks
    @q = current_user.bookmark_posts.ransack(params[:q])
    @bookmark_posts = @q.result(distinct: true).includes(:user, :taggings).order(created_at: :desc).page(params[:page])
  end

  # 送信待ちの投稿一覧
  def scheduled
    @posts = current_user.posts.where('published_at > ?', Time.current).order(created_at: :desc).page(params[:page])
  end

  # 受け取った飯投稿一覧
  def received
    @received_posts = current_user.received_posts.includes(:user, :taggings).where('published_at IS NULL OR published_at <= ?', Time.current).order(created_at: :desc).page(params[:page])
  end

  def search_tags
    query = params[:query]
    @tags = ActsAsTaggableOn::Tag.where('name LIKE ?', "%#{query}%")
    render json: @tags.pluck(:name)
  end

  # レコメンド
  def recommended
    @q = current_user.recommended_posts.ransack(params[:q])
    @recommended_posts = @q.result(distinct: true).includes(:user, :taggings).order(created_at: :desc).page(params[:page])
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def set_recipient_ids
    return unless params[:post][:send_option].present?

    case params[:post][:send_option]
    when 'all'
      params[:post][:recipient_ids] = User.all.pluck(:id)
    when 'random_10'
      params[:post][:recipient_ids] = User.order("RANDOM()").limit(10).pluck(:id)
    end
  end

  def post_params
    params.require(:post).permit(:title, :content, :food_image, :food_image_cache, :tag_list, :published_at, recipient_ids: [])
  end
end

app/views/posts/_bookmark.html.erb
<%= turbo_frame_tag dom_id(post, :bookmark) do %>
  <%= link_to bookmarks_path(post_id: post.id), class: 'float-right', style: 'text-decoration:none', data: { "turbo-method": :post }, remote: true do %>
    <i class="bi bi-suit-heart"></i><%= post.bookmarks.count %>いいね！
  <% end %>
<% end %>

app/views/posts/_crud_menus.html.erb
<ul class="crud-menu-btn list-inline justify-content-center" style="float: right;">
  <li class="list-inline-item">
    <%= link_to edit_post_path(post), id: 'button-edit-#{post.id}' do %>
      <i class="bi bi-pen"></i>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to post_path(post), data: { turbo_method: :delete, turbo_confirm: t('defaults.message.delete_confirm') }  do %>
      <i class="bi bi-trash"></i>
    <% end %>
  </li>
</ul>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true, id: 'post_form' do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :title, class: 'required' %>
    <%= f.text_field :title, class: 'form-control', placeholder: '必須', id: 'post_title', required: true %>
    <div class="invalid-feedback">
      飯名は必須です
    </div>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :content, class: 'required' %>
    <%= f.text_area :content, class: 'form-control', rows: 10, placeholder: '感想や店名、送り相手への煽りなどご自由に！(必須)', id: 'post_content', required: true %>
    <div class="invalid-feedback">
      コメントは必須です
    </div>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :food_image %>
    <%= f.file_field :food_image, class: 'form-control mb-3',
        accept: 'image/*', onchange: 'previewImage()' %>
    <%= f.hidden_field :food_image_cache %>
  </div>
  <br>
  <div class="mt-3 mb-3">
    <%= image_tag post.food_image.url,
                  id: 'preview',
                  size: '300x200' %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, class: 'form-control', value: post.tag_list.join('、'), placeholder: '、で区切って入力してください' %>
  </div>
  <br>
  <div class="form-group">
    <% if post.new_record? || (post.published_at.present? && post.published_at > Time.current) %>
      <%= f.label :published_at %>
      <%= f.datetime_field :published_at, class: 'form-control' %>
    <% end %>
  </div>
  <br>
  <div class="form-group">
    <% if post.new_record? || (post.published_at.present? && post.published_at > Time.current) %>
      <%= f.label :recipients %>
      <div class="dropup">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t('posts.new.recipients') %>
        </button>
        <div class="dropdown-menu scrollable-dropdown dropdown-menu-padding" aria-labelledby="dropdownMenuButton">
          <%= f.collection_check_boxes :recipient_ids, User.all, :id, :display_name do |b| %>
            <div class="form-check">
              <%= b.check_box class: 'form-check-input' %>
              <%= b.label { b.object.display_name.presence || b.object.name } %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.radio_button :send_option, 'all', id: 'send_to_all', class: 'form-check-input' %>
    <%= f.label :send_option_all, for: 'send_to_all' %>
  </div>
  <div class="form-group">
    <%= f.radio_button :send_option, 'random_10', id: 'send_to_random_10', class: 'form-check-input' %>
    <%= f.label :send_option_random_10, for: 'send_to_random_10' %>
  </div>
  <br>
  <br>
  <%= f.submit t('posts.new.title'), class: 'btn btn-warning btn-lg d-grid gap-2 col-6 mx-auto' %>
<% end %>
  <br>

app/views/posts/_index_header.html.erb
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <%= render 'search_form', url: posts_path %>
      </form>
      <ul class="nav nav-tabs mb-6 justify-content-center" id="tab" role="tablist">
        <li class="nav-item ms-0" role="presentation">
          <a class="nav-link <%= active_class_for('posts', 'index') %>" href="<%= posts_path %>" role="tab"><%= t('posts.index.new_post') %></a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link <%= active_class_for('posts', 'top_rated') %>" href="<%= top_rated_posts_path %>" role="tab"><%= t('posts.index.top_rated_post') %></a>
        </li>
        <% if current_user %>
          <li class="nav-item" role="presentation">
            <a class="nav-link <%= active_class_for('posts', 'recommended') %>" href="<%= recommended_posts_path %>" role="tab"><%= t('posts.index.recommended_post') %></a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

app/views/posts/_pagination.html.erb
<div class="row">
  <div class="col-12">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="col-sm-12 col-lg-4 mb-3 grow-on-hover">
  <div class="mb-3 border p-4 bg-light">
    <div class="card">
      <%= link_to post_path(post) do %>
        <%= image_tag post.food_image.url, class: 'card-img-top', size: '300x200' %>
      <% end %>
      <div class="card-body">
        <h4 class="card-title">
          <a href="#"><%= link_to post.title, post_path(post) %></a>
        </h4>
          <% if current_user && current_user.own?(post) %>
            <%= render 'crud_menus', post: post %>
          <% end %>
        <ul class="list-inline">
          <%= image_tag post.user.avatar.url, class: 'rounded-circle', size: '40x40' %>
          <% if post.user.nickname.present? %>
            <%= post.user.nickname %>
          <% else %>
            <%= post.user.name %>
          <% end %>
        </ul>
        <%= render 'tag_list', post: post %>
        <p class="card-text"><%= truncate(post.content, length: 40, omission: '...') %></p>
          <% if current_user %>
            <div style="text-align: right;"><%= render 'bookmark_button', post: post %></div>
          <% end %>
          <% character = [0x1D54F].pack('U*') %>
          <%= link_to "#{character}", "https://twitter.com/intent/tweet?url=https://meshitelog.com/posts/#{post.id}&text=【#{post.title}】をテロ!%0a%20%23飯テログ", class: "btn btn-dark btn-sm", title: 'Twitter', target: '_blank' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div class="row mb-3">
    <div class="col-md-6 mb-2">
      <%= f.search_field :title_cont, class: 'form-control', placeholder: t('defaults.search_word') %>
    </div>
    <div class="col-md-4 mb-2 position-relative">
      <%= f.search_field :tag_name_cont, class: 'form-control', placeholder: t('defaults.search_tag') %>
      <ul class="tag-dropdown" style="display:none;"></ul>
    </div>
    <div class="col-md-2">
      <%= f.submit class: 'btn btn-primary mb-2' %>
      <%= link_to t('defaults.search_reset'), posts_path, class: "btn btn-outline-secondary mb-2" %>
    </div>
  </div>
<% end %>

app/views/posts/_tag_list.html.erb
<% colors = ['primary', 'success', 'info', 'warning', 'danger', 'secondary'] %>
<% post.tag_list.each do |tag| %>
  <span class="badge rounded-pill bg-<%= colors.sample %> text-decoration-none text-white"><%= link_to tag, posts_path(tag_name: tag), class: 'text-white underline_none' %></span>
<% end %>

app/views/posts/_unbookmark.html.erb
<%= turbo_frame_tag dom_id(post, :bookmark) do %>
	<%= link_to bookmark_path(current_user.bookmarks.find_by(post_id: post.id)), style: 'text-decoration:none', class: 'float-right', data: { turbo_method: :delete } do %>
		<i class="bi bi-arrow-through-heart-fill"></i><%= post.bookmarks.count %>いいね！
	<% end %>
<% end %>

app/views/posts/index.html.erb
<% assign_meta_tags title: t('.title') %>
<div class="container pt-3">

  <%= render 'index_header' %>
  <br>
  <!-- 投稿一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @posts.present? %>
          <%= render partial: 'post', collection: @posts, as: :post %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <!-- ページネーション -->
      <%= render 'pagination', posts: @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% assign_meta_tags title: t('.title') %>
<br>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/received.html.erb
<% assign_meta_tags title: t('.title') %>
<div class="container pt-3">

  <!-- 投稿一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @received_posts.present? %>
          <%= render @received_posts %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <!-- ページネーション -->
      <div class="row">
        <div class="col-12">
          <%= paginate @received_posts %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/recommended.html.erb
<% assign_meta_tags title: t('.title') %>
<div class="container pt-3">

  <%= render 'index_header' %>

  <br>
  <!-- 投稿一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @recommended_posts.present? %>
          <%= render @recommended_posts %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/scheduled.html.erb
<% assign_meta_tags title: t('.title') %>
<div class="container pt-3">
  <!-- 予約投稿一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @posts.present? %>
          <%= render @posts %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <!-- ページネーション -->
      <div class="row">
        <div class="col-12">
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>
</div>